#!/bin/bash
# FIRST_RUN.sh — BeigeBox setup wizard (like Claude's /init)
# Auto-detects your system, asks 2 simple questions, sets up everything
# Run once. After that, ./launch.sh just works.

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

CONFIG_DIR="$HOME/.beigebox"
CONFIG_FILE="$CONFIG_DIR/config"

# Banner
echo ""
echo -e "${BLUE}  BeigeBox Setup${NC}"
echo -e "${BLUE}  ══════════════${NC}"
echo ""

# Auto-detect platform
PLATFORM=$(uname -s)
ARCH=$(uname -m)

if [[ "$PLATFORM" == "Darwin" ]]; then
    DISPLAY_PLATFORM="macOS"
    IS_MACOS=true
else
    DISPLAY_PLATFORM="Linux"
    IS_MACOS=false
fi

if [[ "$ARCH" == "arm64" || "$ARCH" == "aarch64" ]]; then
    DISPLAY_ARCH="ARM64"
    IS_ARM64=true
else
    DISPLAY_ARCH="x86_64"
    IS_ARM64=false
fi

echo -e "${GREEN}✓${NC} Detected: $DISPLAY_PLATFORM ($DISPLAY_ARCH)"
echo ""

# Question 1: What do you want to do?
echo -e "${YELLOW}What's your main use case?${NC}"
echo ""
echo "  1. LLM inference only (default)"
echo "  2. + Speech I/O (voice/STT/TTS)"
echo "  3. + Browser automation (CDP)"
echo "  4. Everything (voice + browser)"
echo ""

read -p "Choose [1-4, default 1]: " -r USE_CASE
USE_CASE=${USE_CASE:-1}

PROFILES=""
case "$USE_CASE" in
    2)
        if $IS_MACOS && $IS_ARM64; then
            PROFILES="apple"
            echo -e "${GREEN}✓${NC} Will add: native arm64 voice I/O"
        else
            PROFILES="voice"
            echo -e "${GREEN}✓${NC} Will add: voice I/O"
        fi
        ;;
    3)
        PROFILES="cdp"
        echo -e "${GREEN}✓${NC} Will add: browser automation"
        ;;
    4)
        if $IS_MACOS && $IS_ARM64; then
            PROFILES="apple,cdp"
            echo -e "${GREEN}✓${NC} Will add: native voice I/O + browser automation"
        else
            PROFILES="voice,cdp"
            echo -e "${GREEN}✓${NC} Will add: voice I/O + browser automation"
        fi
        ;;
    *)
        echo -e "${GREEN}✓${NC} Core only: LLM inference + proxy"
        ;;
esac

echo ""

# Question 2: Models location
echo -e "${YELLOW}Where should models be stored?${NC}"
echo ""

if $IS_MACOS; then
    DEFAULT_OLLAMA_DATA="/Users/$(whoami)/.ollama"
else
    DEFAULT_OLLAMA_DATA="/home/$(whoami)/.ollama"
fi

echo "  Default: $DEFAULT_OLLAMA_DATA"
echo "  Custom path? Press Enter for default, or paste path:"
echo ""

read -p "> " -r CUSTOM_OLLAMA_DATA

if [[ -n "$CUSTOM_OLLAMA_DATA" ]]; then
    OLLAMA_DATA="$CUSTOM_OLLAMA_DATA"
else
    OLLAMA_DATA="$DEFAULT_OLLAMA_DATA"
fi

echo -e "${GREEN}✓${NC} Models → $OLLAMA_DATA"
echo ""

# Create config
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# BeigeBox Config — auto-generated by FIRST_RUN.sh
# To re-run setup: rm $CONFIG_FILE && ./FIRST_RUN.sh

PLATFORM=$PLATFORM
ARCH=$ARCH
PROFILES=$PROFILES
OLLAMA_DATA=$OLLAMA_DATA
OLLAMA_PORT=11434
BEIGEBOX_PORT=1337
WHISPER_PORT=9000
KOKORO_PORT=8880
CHROME_PORT=9222
EOF

chmod 600 "$CONFIG_FILE"

# Update docker/.env
cd "$(dirname "$0")"
if [[ ! -f .env ]]; then
    cp env.example .env
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "s|^OLLAMA_DATA=.*|OLLAMA_DATA=$OLLAMA_DATA|" .env || true
    sed -i '' "s|^REQUIRE_HASHES=.*|REQUIRE_HASHES=false|" .env || true
else
    sed -i "s|^OLLAMA_DATA=.*|OLLAMA_DATA=$OLLAMA_DATA|" .env || true
    sed -i "s|^REQUIRE_HASHES=.*|REQUIRE_HASHES=false|" .env || true
fi

echo ""
echo -e "${BLUE}  Ready to launch!${NC}"
echo -e "${BLUE}  ════════════════${NC}"
echo ""
echo -e "${YELLOW}Next:${NC} docker/launch.sh up -d"
echo -e "${YELLOW}Then:${NC} open http://localhost:1337"
echo ""
