#!/bin/bash
# FIRST_RUN.sh — Interactive BeigeBox Docker setup wizard
# Detects platform, asks for profile choices, creates ~/.beigebox/config
# Run this once. After that, use ./launch.sh

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

CONFIG_DIR="$HOME/.beigebox"
CONFIG_FILE="$CONFIG_DIR/config"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}BeigeBox Docker Setup Wizard${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Detect platform
PLATFORM=$(uname -s)
ARCH=$(uname -m)

if [[ "$PLATFORM" == "Darwin" ]]; then
    DISPLAY_PLATFORM="macOS"
    IS_MACOS=true
else
    DISPLAY_PLATFORM="Linux"
    IS_MACOS=false
fi

if [[ "$ARCH" == "arm64" || "$ARCH" == "aarch64" ]]; then
    DISPLAY_ARCH="ARM64"
    IS_ARM64=true
else
    DISPLAY_ARCH="x86_64"
    IS_ARM64=false
fi

echo -e "${GREEN}✓ Detected: $DISPLAY_PLATFORM ($DISPLAY_ARCH)${NC}"
echo ""

# Step 2: Ask which profiles
echo -e "${YELLOW}Which profiles do you want? (select all that apply)${NC}"
echo ""

declare -a AVAILABLE_PROFILES
declare -a PROFILE_DESCS

if $IS_MACOS && $IS_ARM64; then
    AVAILABLE_PROFILES+=("apple")
    PROFILE_DESCS+=("STT + TTS (native arm64 voice I/O) — RECOMMENDED")
else
    AVAILABLE_PROFILES+=("voice")
    PROFILE_DESCS+=("STT + TTS (x86_64/Linux speech I/O)")
fi

AVAILABLE_PROFILES+=("cdp")
PROFILE_DESCS+=("Chrome browser automation (CDP)")

AVAILABLE_PROFILES+=("engines-vllm")
PROFILE_DESCS+=("Production inference (faster than Ollama)")

AVAILABLE_PROFILES+=("engines-cpp")
PROFILE_DESCS+=("Lightweight C++ inference (quantized models)")

AVAILABLE_PROFILES+=("sandbox")
PROFILE_DESCS+=("Claude Code sidecar (AI assistant with workspace access)")

# Display options
for i in "${!AVAILABLE_PROFILES[@]}"; do
    profile="${AVAILABLE_PROFILES[$i]}"
    desc="${PROFILE_DESCS[$i]}"
    echo "  [$i] $profile — $desc"
done

echo ""
echo "Enter profile numbers (space-separated, e.g. '0 1 2') or press Enter for none:"
read -p "> " -r PROFILE_INPUT

SELECTED_PROFILES=()
if [[ -n "$PROFILE_INPUT" ]]; then
    for idx in $PROFILE_INPUT; do
        if [[ $idx -lt ${#AVAILABLE_PROFILES[@]} ]]; then
            SELECTED_PROFILES+=("${AVAILABLE_PROFILES[$idx]}")
        fi
    done
fi

echo ""
if [[ ${#SELECTED_PROFILES[@]} -gt 0 ]]; then
    echo -e "${GREEN}✓ Selected profiles:${NC}"
    for profile in "${SELECTED_PROFILES[@]}"; do
        echo "    - $profile"
    done
else
    echo -e "${YELLOW}⚠ No optional profiles selected (core only: ollama + beigebox)${NC}"
fi

# Step 3: Set OLLAMA_DATA path
echo ""
echo -e "${YELLOW}Where should Ollama store models?${NC}"

if $IS_MACOS; then
    DEFAULT_OLLAMA_DATA="/Users/$(whoami)/.ollama"
else
    DEFAULT_OLLAMA_DATA="/home/$(whoami)/.ollama"
fi

echo "Default: $DEFAULT_OLLAMA_DATA"
echo "Press Enter to use default, or enter custom path:"
read -p "> " -r CUSTOM_OLLAMA_DATA

if [[ -n "$CUSTOM_OLLAMA_DATA" ]]; then
    OLLAMA_DATA="$CUSTOM_OLLAMA_DATA"
else
    OLLAMA_DATA="$DEFAULT_OLLAMA_DATA"
fi

echo -e "${GREEN}✓ OLLAMA_DATA: $OLLAMA_DATA${NC}"

# Step 4: Create config directory and file
mkdir -p "$CONFIG_DIR"

# Build profile string (comma-separated for launch.sh)
PROFILE_STRING=$(IFS=,; echo "${SELECTED_PROFILES[*]}")

# Write config
cat > "$CONFIG_FILE" << EOF
# BeigeBox Docker Configuration
# Generated by FIRST_RUN.sh — edit to change settings
# Run 'rm $CONFIG_FILE && $0' to re-run setup

PLATFORM=$PLATFORM
ARCH=$ARCH
DISPLAY_PLATFORM=$DISPLAY_PLATFORM
DISPLAY_ARCH=$DISPLAY_ARCH
IS_MACOS=$IS_MACOS
IS_ARM64=$IS_ARM64

# Selected profiles (space-separated for docker compose --profile)
PROFILES=$PROFILE_STRING

# Ollama model storage path
OLLAMA_DATA=$OLLAMA_DATA

# Docker ports (customizable)
OLLAMA_PORT=11434
BEIGEBOX_PORT=1337
WHISPER_PORT=9000
KOKORO_PORT=8880
CHROME_PORT=9222

# Optional: API keys for external services
# GOOGLE_API_KEY=
# GOOGLE_CSE_ID=
# ANTHROPIC_API_KEY=
EOF

chmod 600 "$CONFIG_FILE"
echo -e "${GREEN}✓ Config saved to: $CONFIG_FILE${NC}"

# Step 5: Create/update docker/.env
cd "$(dirname "$0")"
if [[ ! -f .env ]]; then
    cp env.example .env
    echo -e "${GREEN}✓ Created docker/.env from env.example${NC}"
fi

# Update OLLAMA_DATA in .env
if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "s|^OLLAMA_DATA=.*|OLLAMA_DATA=$OLLAMA_DATA|" .env || true
else
    sed -i "s|^OLLAMA_DATA=.*|OLLAMA_DATA=$OLLAMA_DATA|" .env || true
fi

# Update REQUIRE_HASHES (dev default: false, prod: true)
if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "s|^REQUIRE_HASHES=.*|REQUIRE_HASHES=false|" .env || true
else
    sed -i "s|^REQUIRE_HASHES=.*|REQUIRE_HASHES=false|" .env || true
fi

echo -e "${GREEN}✓ Updated docker/.env${NC}"
echo ""

# Step 6: Summary and next steps
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Setup complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Summary:"
echo "  Platform: $DISPLAY_PLATFORM ($DISPLAY_ARCH)"
echo "  Profiles: ${PROFILE_STRING:-none}"
echo "  OLLAMA_DATA: $OLLAMA_DATA"
echo "  Config: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Make sure Docker Desktop is running"
echo "  2. Run: cd docker && ./launch.sh up -d"
echo "  3. Open: http://localhost:1337"
echo ""
echo -e "${YELLOW}Note:${NC} To change settings later, edit $CONFIG_FILE or run this script again."
echo ""
